version: '3.8'

services:
  redis-master:
    image: bitnami/redis:5.0-debian-9
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: pass1234
    ports:
      - 6379:6379

  redis-sentinel:
    image: bitnami/redis-sentinel:5.0-debian-9
    depends_on: [ redis-master ]
    environment:
      REDIS_MASTER_HOST: 127.0.0.1
      REDIS_MASTER_PORT_NUMBER: 6379
      REDIS_MASTER_SET: redis-master-set
      REDIS_MASTER_PASSWORD: pass1234
      # Uncomment this env-var to enable Sentinel authentication.
      #REDIS_SENTINEL_PASSWORD: pass1234
    ports:
      - 26379:26379
